
"""
Django settings for stayslay project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.urls import reverse_lazy
import logging
BASE_DIR = Path(__file__).resolve().parent.parent
GOOGLE_OAUTH2_SCOPES = [
    'openid',  # Required for user identification
    'https://www.googleapis.com/auth/userinfo.email', # Required to get email
    'https://www.googleapis.com/auth/userinfo.profile', # Recommended to get name
    'https://www.googleapis.com/auth/gmail.readonly', # Your existing scope
    'https://www.googleapis.com/auth/gmail.modify' , # Your existing scope
]
CREDENTIALS_JSON_PATH = "/var/www/gmailtool/Gmail_Tool/credentials/credentials.json"
# Ensure these are all defined:
GOOGLE_CLIENT_ID = '105754817720-vset9poiiqpof5df6hpmvssmcr4dh9ps.apps.googleusercontent.com'
GOOGLE_CLIENT_SECRET = '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' # STORE SECURELY
GOOGLE_TOKEN_URI = 'https://oauth2.googleapis.com/token'  # *** ADD THIS LINE ***

APSCHEDULER_JOBSTORES = {
    'default': {
        'type': 'memory'
    }
}
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # Seconds
LOGIN_URL = reverse_lazy('login')


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC' # <-- DEFINED HERE

USE_I18N = True

USE_TZ = True

# ... (SESSION_COOKIE_SECURE, CSRF_COOKIE_SECURE, STATIC_URL etc.)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}


# Celery Configuration Options  <-- PASTED HERE
# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Redis is used as the message broker
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # Store results in Redis
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE  # Assuming your TIME_ZONE variable is set

# Celery Beat Schedule (periodic tasks)
CELERY_BEAT_SCHEDULE = {
    'check_and_schedule_deletion': {
        'task': 'gmailtool.tasks.check_and_schedule_deletion',
        'schedule': 60.0,  # Runs every minute (adjust as needed)
    },
}
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z&^7n7@(gw5575um-bb9aem(bl8)km-)ah0bs$eg042=&&k&7v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['inbox-detox.com', 'www.inbox-detox.com', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gmailtool',
    'django_apscheduler',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stayslay.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stayslay.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
SESSION_ENGINE = 'django.contrib.sessions.backends.db'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/




SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
GOOGLE_OAUTH_REDIRECT_URI = 'https://inbox-detox.com/oauth2callback/'