# Generated by Django 5.2 on 2025-04-25 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('gmailtool', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Alter model options first (usually fine)
        migrations.AlterModelOptions(
            name='scheduledsender',
            options={'verbose_name': 'Auto Delete Rule', 'verbose_name_plural': 'Auto Delete Rules'},
        ),

        # 2. Add the 'user' field *BEFORE* using it in unique_together
        #    Keep the default=1 if Django added it (implies you might have existing rows)
        #    Make sure user with ID 1 exists, or handle existing rows differently (e.g., delete them)
        migrations.AddField(
            model_name='scheduledsender',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auto_delete_rules', to=settings.AUTH_USER_MODEL),
            # Note: If you added default=1 during makemigrations for existing rows,
            # you might need preserve_default=False here depending on Django version
            # and if you want it to be the permanent default. But usually keeping
            # what makemigrations generated is correct for the migration itself.
        ),

        # 3. Now apply the unique_together constraint
        migrations.AlterUniqueTogether(
            name='scheduledsender',
            unique_together={('user', 'sender_email')},
        ),

        # 4. Add other fields
        migrations.AddField(
            model_name='scheduledsender',
            name='days_to_keep',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scheduledsender',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scheduledsender',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),

        # 5. Alter sender_email (fine here)
        migrations.AlterField(
            model_name='scheduledsender',
            name='sender_email',
            field=models.EmailField(max_length=255),
        ),

        # 6. Remove the old credentials field (usually fine at the end)
        migrations.RemoveField(
            model_name='scheduledsender',
            name='credentials',
        ),
    ]