# Generated by Django 5.2 on 2025-04-28 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailtool', '0003_senderanalysisresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledsender',
            options={'ordering': ['user', 'sender_email'], 'verbose_name': 'Scheduled Deletion Rule', 'verbose_name_plural': 'Scheduled Deletion Rules'},
        ),
        migrations.RemoveField(
            model_name='scheduledsender',
            name='days_to_keep',
        ),
        migrations.AddField(
            model_name='scheduledsender',
            name='delete_older_than_days',
            field=models.PositiveIntegerField(choices=[(3, '3 Days'), (5, '5 Days'), (7, '7 Days')], default=3),
        ),
        migrations.AlterField(
            model_name='scheduledsender',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_deletion_rules', to=settings.AUTH_USER_MODEL),
        ),
    ]
