# Generated by Django 5.2 on 2025-04-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailtool', '0004_alter_scheduledsender_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senderanalysisresult',
            name='celery_task_id',
        ),
        migrations.AddField(
            model_name='senderanalysisresult',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, help_text='Celery task ID if applicable', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledsender',
            name='delete_older_than_days',
            field=models.PositiveIntegerField(default=1, help_text='Fixed rule: Deletes emails older than this many days (always 1).'),
        ),
    ]
