# Generated by Django 5.2 on 2025-04-29 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailtool', '0005_remove_senderanalysisresult_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledsender',
            options={'ordering': ['user', 'sender_email'], 'verbose_name': 'Scheduled Deletion Rule (1 Day)', 'verbose_name_plural': 'Scheduled Deletion Rules (1 Day)'},
        ),
        migrations.AddField(
            model_name='senderanalysisresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduledsender',
            name='delete_older_than_days',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Fixed rule: Deletes emails older than 1 day.'),
        ),
        migrations.AlterField(
            model_name='scheduledsender',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='scheduledsender',
            name='sender_email',
            field=models.EmailField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='senderanalysisresult',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when task finished (Completed or Failed)', null=True),
        ),
        migrations.AlterField(
            model_name='senderanalysisresult',
            name='error_message',
            field=models.TextField(blank=True, help_text='Details of the last critical error', null=True),
        ),
        migrations.AlterField(
            model_name='senderanalysisresult',
            name='sender_counts',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary of {sender_email: count}', null=True),
        ),
        migrations.AlterField(
            model_name='senderanalysisresult',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when task processing began', null=True),
        ),
        migrations.AlterField(
            model_name='senderanalysisresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('TRIGGERED', 'Triggered'), ('FAILED_TO_START', 'Failed to Start')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='senderanalysisresult',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, help_text='Celery task ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='senderanalysisresult',
            name='total_errors_encountered',
            field=models.PositiveIntegerField(default=0, help_text='Errors during message processing/batch execution'),
        ),
        migrations.AlterField(
            model_name='senderanalysisresult',
            name='total_ids_fetched',
            field=models.PositiveIntegerField(default=0, help_text='Total message IDs fetched initially'),
        ),
        migrations.AlterField(
            model_name='senderanalysisresult',
            name='total_messages_processed',
            field=models.PositiveIntegerField(default=0, help_text='Messages successfully processed for sender info'),
        ),
        migrations.AlterField(
            model_name='senderanalysisresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of last update'),
        ),
    ]
