# Generated by Django 5.2 on 2025-04-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailtool', '0006_alter_scheduledsender_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senderanalysisresult',
            name='task_id',
        ),
        migrations.AddField(
            model_name='senderanalysisresult',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledsender',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scheduledsender',
            name='sender_email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='senderanalysisresult',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='senderanalysisresult',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='senderanalysisresult',
            name='sender_counts',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='senderanalysisresult',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='senderanalysisresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='senderanalysisresult',
            name='total_errors_encountered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='senderanalysisresult',
            name='total_ids_fetched',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='senderanalysisresult',
            name='total_messages_processed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='senderanalysisresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
