# Generated by Django 5.2 on 2025-04-29 05:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailtool', '0007_remove_senderanalysisresult_task_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senderanalysisresult',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='senderanalysisresult',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
