# Generated by Django 5.2 on 2025-04-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailtool', '0008_remove_senderanalysisresult_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledsender',
            options={'ordering': ['user', 'sender_email'], 'verbose_name': 'Scheduled Deletion Rule', 'verbose_name_plural': 'Scheduled Deletion Rules'},
        ),
        migrations.AlterField(
            model_name='scheduledsender',
            name='delete_older_than_days',
            field=models.PositiveIntegerField(choices=[(3, '3 Days'), (5, '5 Days'), (7, '7 Days')], default=3),
        ),
    ]
