# Generated by Django 5.2 on 2025-04-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailtool', '0009_alter_scheduledsender_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledsender',
            options={'ordering': ['user', 'sender_email'], 'verbose_name': 'Scheduled Deletion Rule (1 Day)', 'verbose_name_plural': 'Scheduled Deletion Rules (1 Day)'},
        ),
        migrations.AlterField(
            model_name='scheduledsender',
            name='delete_older_than_days',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Fixed rule: Deletes emails older than 1 day.'),
        ),
    ]
