# Generated by Django 5.2 on 2025-04-29 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailtool', '0010_alter_scheduledsender_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledsender',
            options={'verbose_name': 'Auto Delete Rule', 'verbose_name_plural': 'Auto Delete Rules'},
        ),
        migrations.RemoveField(
            model_name='scheduledsender',
            name='delete_older_than_days',
        ),
        migrations.AddField(
            model_name='scheduledsender',
            name='days_to_keep',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='scheduledsender',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auto_delete_rules', to=settings.AUTH_USER_MODEL),
        ),
    ]
