# Generated by Django 5.2 on 2025-04-29 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailtool', '0011_alter_scheduledsender_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledsender',
            options={'verbose_name': 'Scheduled Sender Rule', 'verbose_name_plural': 'Scheduled Sender Rules'},
        ),
        migrations.RenameField(
            model_name='scheduledsender',
            old_name='days_to_keep',
            new_name='older_than_days',
        ),
        migrations.AlterField(
            model_name='scheduledsender',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='scheduledsender',
            name='sender_email',
            field=models.EmailField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduledsender',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_senders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='scheduledsender',
            index=models.Index(fields=['user', 'is_active'], name='gmailtool_s_user_id_1d32e0_idx'),
        ),
    ]
