# Generated by Django 5.2 on 2025-04-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmailtool', '0012_alter_scheduledsender_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senderanalysisresult',
            name='user',
        ),
        migrations.DeleteModel(
            name='ScheduledSender',
        ),
        migrations.DeleteModel(
            name='SenderAnalysisResult',
        ),
    ]
