# Generated by Django 5.2 on 2025-04-29 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailtool', '0014_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(db_index=True, help_text='The email address of the sender whose emails should be managed.', max_length=254)),
                ('older_than_days', models.PositiveIntegerField(default=1, help_text='Delete emails from this sender older than this many days.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'sender_email'],
                'unique_together': {('user', 'sender_email')},
            },
        ),
    ]
