# Generated by Django 5.2 on 2025-05-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailtool', '0015_deletionrule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduledsender',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scheduledsender',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='senderanalysisresult',
            options={'ordering': ['-started_at'], 'verbose_name': 'Sender Analysis Result', 'verbose_name_plural': 'Sender Analysis Results'},
        ),
        migrations.AddField(
            model_name='senderanalysisresult',
            name='task_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DeletionRule',
        ),
        migrations.DeleteModel(
            name='ScheduledSender',
        ),
    ]
