# Generated by Django 5.2 on 2025-05-08 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailtool', '0016_alter_scheduledsender_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(blank=True, help_text='Google OAuth refresh token.', max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The Django user associated with this token.', on_delete=django.db.models.deletion.CASCADE, related_name='google_oauth_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User OAuth Token',
                'verbose_name_plural': 'User OAuth Tokens',
            },
        ),
        migrations.CreateModel(
            name='ScheduledDeletionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email_to_delete', models.EmailField(help_text='The email address of the sender whose emails should be deleted.', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Is this rule currently active and should be processed?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Timestamp of the last time this rule was processed by a background task.', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Stores the last error message if processing this rule failed.', null=True)),
                ('user', models.ForeignKey(help_text='The user who created this rule.', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_deletion_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheduled Deletion Rule',
                'verbose_name_plural': 'Scheduled Deletion Rules',
                'ordering': ['user', 'sender_email_to_delete'],
                'unique_together': {('user', 'sender_email_to_delete')},
            },
        ),
    ]
