# Generated by Django 5.2 on 2025-05-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmailtool', '0017_useroauthtoken_scheduleddeletionrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useroauthtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='ScheduledDeletionRule',
        ),
        migrations.DeleteModel(
            name='UserOAuthToken',
        ),
    ]
